import {
  Leaf,
  Flame,
  Droplets,
  Zap,
  Bug,
  Skull,
  Mountain,
  Bird,
  Brain,
  Ghost,
  Sword,
  Moon,
  Snowflake,
  Gem,
  Shield,
  CircleDot,
  Sparkles,
} from "lucide-react";

export const TYPE_TRANSLATION = {
  plante: "grass",
  poison: "poison",
  feu: "fire",
  eau: "water",
  vol: "flying",
  insecte: "bug",
  normal: "normal",
  electrik: "electric",
  électrik: "electric",
  sol: "ground",
  fée: "fairy",
  fee: "fairy",
  combat: "fighting",
  psy: "psychic",
  roche: "rock",
  acier: "steel",
  glace: "ice",
  spectre: "ghost",
  dragon: "dragon",
  ténèbres: "dark",
  tenebres: "dark",
  ombre: "dark",
};

export const TYPE_ICONS = {
  normal: <CircleDot className="w-3 h-3" />,
  fire: <Flame className="w-3 h-3" />,
  water: <Droplets className="w-3 h-3" />,
  electric: <Zap className="w-3 h-3" />,
  grass: <Leaf className="w-3 h-3" />,
  ice: <Snowflake className="w-3 h-3" />,
  fighting: <Sword className="w-3 h-3" />,
  poison: <Skull className="w-3 h-3" />,
  ground: <Mountain className="w-3 h-3" />,
  flying: <Bird className="w-3 h-3" />,
  psychic: <Brain className="w-3 h-3" />,
  bug: <Bug className="w-3 h-3" />,
  rock: <Mountain className="w-3 h-3" />,
  ghost: <Ghost className="w-3 h-3" />,
  dragon: <Sparkles className="w-3 h-3" />,
  dark: <Moon className="w-3 h-3" />,
  steel: <Shield className="w-3 h-3" />,
  fairy: <Gem className="w-3 h-3" />,
  default: <CircleDot className="w-3 h-3" />,
};

export const TYPE_STYLES = {
  normal: {
    bg: "bg-gray-500",
    glow: "from-gray-500 to-gray-600",
    text: "text-gray-500",
  },
  fire: {
    bg: "bg-orange-500",
    glow: "from-orange-500 to-orange-600",
    text: "text-orange-500",
  },
  water: {
    bg: "bg-blue-500",
    glow: "from-blue-500 to-blue-600",
    text: "text-blue-500",
  },
  electric: {
    bg: "bg-yellow-400",
    glow: "from-yellow-400 to-yellow-500",
    text: "text-yellow-400",
  },
  grass: {
    bg: "bg-green-500",
    glow: "from-green-500 to-green-600",
    text: "text-green-500",
  },
  ice: {
    bg: "bg-cyan-300",
    glow: "from-cyan-300 to-blue-300",
    text: "text-cyan-300",
  },
  fighting: {
    bg: "bg-red-600",
    glow: "from-red-600 to-red-700",
    text: "text-red-600",
  },
  poison: {
    bg: "bg-purple-600",
    glow: "from-purple-600 to-purple-700",
    text: "text-purple-600",
  },
  ground: {
    bg: "bg-amber-600",
    glow: "from-amber-600 to-amber-700",
    text: "text-amber-600",
  },
  flying: {
    bg: "bg-indigo-400",
    glow: "from-indigo-400 to-indigo-500",
    text: "text-indigo-400",
  },
  psychic: {
    bg: "bg-pink-500",
    glow: "from-pink-500 to-pink-600",
    text: "text-pink-500",
  },
  bug: {
    bg: "bg-lime-500",
    glow: "from-lime-500 to-lime-600",
    text: "text-lime-500",
  },
  rock: {
    bg: "bg-stone-500",
    glow: "from-stone-500 to-stone-600",
    text: "text-stone-500",
  },
  ghost: {
    bg: "bg-violet-600",
    glow: "from-violet-600 to-violet-700",
    text: "text-violet-600",
  },
  dragon: {
    bg: "bg-gradient-to-r from-purple-600 to-amber-500",
    glow: "from-purple-600 to-amber-500",
    text: "text-transparent bg-clip-text bg-gradient-to-r from-purple-600 to-amber-500",
  },
  dark: {
    bg: "bg-gray-800",
    glow: "from-gray-800 to-gray-900",
    text: "text-gray-800",
  },
  steel: {
    bg: "bg-gray-400",
    glow: "from-gray-400 to-gray-500",
    text: "text-gray-400",
  },
  fairy: {
    bg: "bg-pink-300",
    glow: "from-pink-300 to-pink-400",
    text: "text-pink-300",
  },
  default: {
    bg: "bg-gray-700",
    glow: "from-gray-700 to-gray-800",
    text: "text-gray-700",
  },
};
